const API_BASE_URL = (window.GRIDSCOPE_API_BASE_URL || localStorage.getItem('gridscope_api_base') || (window.location.hostname.endsWith('github.io') ? 'https://gridscope-api-yigedashuaige.onrender.com' : 'http://127.0.0.1:8000')).replace(/\/+$/, '');
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const state = { data: null, date: '2025-02-01', strategy: 'Q3-M3', activeSeries: new Set(['load_kw', 'pv_kw']), question: 'overview', replaySlot: 35, compareMode: 'cost', replayTimer: null, forecastFile: null, solverStatus: 'checking' };
let frozen = {};
function fmt(value, digits = 1) { return Number(value || 0).toLocaleString('zh-CN', { maximumFractionDigits: digits, minimumFractionDigits: digits }); }
function dateData() { return state.data?.days?.[state.date]; }
function selectedStrategy() { return dateData()?.strategies?.[state.strategy] || dateData()?.strategies?.['Q3-M3']; }
function slotLabel(index) { return state.data?.slot_labels?.[index] || `${String(Math.floor((index + 1) / 6) % 24).padStart(2, '0')}:${String((index + 1) % 6 * 10).padStart(2, '0')}`; }
function setSolverStatus(status, note) { state.solverStatus = status; const value = $('#solverStatusValue'); const detail = $('#solverStatusNote'); const retry = $('#solverRetry'); if (value) { value.textContent = status === 'online' ? 'SOLVER ONLINE' : status === 'waking' ? 'SOLVER WAKING' : status === 'offline' ? 'SOLVER OFFLINE' : 'SOLVER CHECKING'; value.dataset.status = status; } if (detail) detail.textContent = note || (status === 'online' ? 'Q1/Q2/Q3/Q4 online' : status === 'waking' ? '正在唤醒优化求解器…' : '在线求解器暂不可用'); if (retry) retry.hidden = status !== 'offline'; }
function showLabError(error) { const message = error?.message || '求解器请求失败'; const hint = state.solverStatus === 'offline' ? ' 请确认 Render 服务已唤醒后重试。' : ''; $('#labError').textContent = `${message}${hint}`; $('#labError').hidden = false; }

async function loadSnapshot() {
  const response = await fetch('data/web_data.json', { cache: 'no-store' });
  if (!response.ok) throw new Error(`snapshot HTTP ${response.status}`);
  state.data = await response.json();
  frozen = state.data.frozen_metrics || {};
  const dates = Object.keys(state.data.days || {});
  if (dates.length) state.date = dates.includes(state.date) ? state.date : dates[0];
  $('#snapshotStatus').textContent = `SNAPSHOT LOADED · ${dates.length} days · 144 slots/day`;
  $('#dateSelect').innerHTML = dates.map(date => `<option value="${date}">${date}</option>`).join(''); $('#dateSelect').value = state.date;
  $('#labBaseDate').innerHTML = dates.map(date => `<option value="${date}">${date}</option>`).join(''); $('#labBaseDate').value = state.date;
  $('#forecastDate').innerHTML = dates.filter(date => date >= '2025-02-26').map(date => `<option value="${date}">${date}</option>`).join(''); $('#forecastDate').value = dates.find(date => date >= '2025-02-26') || dates[0];
  renderDay(); renderCompare(); renderSoc(); layoutTwin();
}
function renderDay() {
  const day = dateData(); if (!day) return; const actual = day.actual; const strategy = selectedStrategy(); const battery = strategy?.battery; const totalPlan = strategy?.plan_kwh?.reduce((a, b) => a + b, 0) || 0; const emergency = strategy?.emergency_events?.reduce((sum, event) => sum + Number(event.energy_kwh || 0), 0) || 0; const startSoc = battery?.soc_kwh?.[0] || 6000;
  const causal = day.causal || {};
  $('#dateKicker').textContent = `HISTORICAL REPLAY · ${state.date.replaceAll('-', ' / ')}`; $('#dateHeading').textContent = `${state.date.slice(5, 7)} 月 ${state.date.slice(8)} 日能量画像`; $('#planValue').innerHTML = `${fmt(totalPlan)} <small>kWh</small>`; $('#socValue').innerHTML = `${fmt(startSoc / 12000 * 100)} <small>%</small>`; $('#socMeta').innerHTML = `<span class="soc-bar"><i style="width:${startSoc / 12000 * 100}%"></i></span><span>${fmt(startSoc)} / 12,000 kWh</span>`; $('#riskValue').textContent = Number(frozen.alpha ?? .70).toFixed(2); $('#emergencyValue').innerHTML = `${fmt(emergency, 0)} <small>kWh</small>`; $('#chartMetric').textContent = `负荷峰值 ${fmt(Math.max(...actual.load_kw), 1)} kW · 光伏峰值 ${fmt(Math.max(...actual.pv_kw), 1)} kW`; $('#predictorTimeline').textContent = `${causal.history_days ?? 28} 日滚动选择 · ${causal.selected_predictor || '历史路径'}`; $('#q1CostValue').innerHTML = frozen.q1_cost_yuan ? `${fmt(frozen.q1_cost_yuan, 2)} <small>元</small>` : '—'; $('#m3PlanCostValue').textContent = frozen.m3_plan_cost_yuan ? `${fmt(frozen.m3_plan_cost_yuan / 1e6, 2)} M` : '—'; $('#q4_2CostValue').textContent = frozen.q4_2_plan_cost_yuan ? `${fmt(frozen.q4_2_plan_cost_yuan / 1e6, 2)} M` : '—'; $('#q4_3CostValue').textContent = frozen.q4_3_plan_cost_yuan ? `${fmt(frozen.q4_3_plan_cost_yuan / 1e6, 2)} M` : '—'; $('#dateSelect').value = state.date; drawProfile(); drawQ4Price(); $('#socTitle').textContent = `SOC 轨迹 · ${state.date.slice(5).replace('-', ' 月 ')} 日`; renderSoc();
}
function drawProfile() {
  const canvas = $('#profileChart'); if (!canvas || !dateData()) return; const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; const width = Math.max(280, rect.width); const height = rect.height || 252; canvas.width = width * dpr; canvas.height = height * dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr, dpr); const actual = dateData().actual; const pad = { l: 43, r: 12, t: 10, b: 20 }; const plotW = width - pad.l - pad.r; const plotH = height - pad.t - pad.b; const maxPower = Math.max(...actual.load_kw, ...actual.pv_kw, 1) * 1.12; const x = i => pad.l + plotW * i / 143; const y = v => pad.t + plotH * (1 - v / maxPower);
  ctx.clearRect(0, 0, width, height); ctx.font = '10px DM Mono, monospace'; ctx.fillStyle = '#97a49d'; ctx.strokeStyle = '#e0e6df'; ctx.lineWidth = 1; for (let i = 0; i < 4; i++) { const yy = pad.t + plotH * i / 3; ctx.beginPath(); ctx.moveTo(pad.l, yy); ctx.lineTo(width - pad.r, yy); ctx.stroke(); ctx.fillText(fmt(maxPower * (1 - i / 3), 0), 1, yy + 4); }
  const line = (key, color, multiplier = 1) => { if (!state.activeSeries.has(key)) return; ctx.beginPath(); actual[key].forEach((value, i) => i ? ctx.lineTo(x(i), y(value * multiplier)) : ctx.moveTo(x(i), y(value * multiplier))); ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.lineJoin = 'round'; ctx.stroke(); for (let i = 0; i < 144; i += 12) { ctx.beginPath(); ctx.fillStyle = color; ctx.arc(x(i), y(actual[key][i] * multiplier), 2.2, 0, Math.PI * 2); ctx.fill(); } }; line('load_kw', '#104680'); line('pv_kw', '#f6b293'); if (state.activeSeries.has('price')) line('price_yuan_kwh', '#b72230', maxPower / Math.max(...actual.price_yuan_kwh, .01));
  canvas.onmousemove = event => { const r = canvas.getBoundingClientRect(); const index = Math.max(0, Math.min(143, Math.round((event.clientX - r.left - pad.l) / plotW * 143))); const tip = $('#chartTooltip'); tip.style.display = 'block'; tip.style.left = `${Math.min(r.width - 165, Math.max(5, event.clientX - r.left + 10))}px`; tip.style.top = `${Math.max(4, event.clientY - r.top - 66)}px`; tip.innerHTML = `<b>${slotLabel(index)}</b><br>负荷 ${fmt(actual.load_kw[index])} kW<br>光伏 ${fmt(actual.pv_kw[index])} kW<br>电价 ${Number(actual.price_yuan_kwh[index]).toFixed(4)} 元/kWh`; }; canvas.onmouseleave = () => { $('#chartTooltip').style.display = 'none'; };
}
function drawQ4Price() { const canvas = $('#q4PriceChart'); const price = dateData()?.causal_price; if (!canvas || !price) return; const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; const width = Math.max(280, rect.width), height = rect.height || 170; canvas.width = width * dpr; canvas.height = height * dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr, dpr); const all = [...price.actual_yuan_kwh, ...price.forecast_yuan_kwh, ...price.baseline_yuan_kwh]; const min = Math.min(...all), max = Math.max(...all, min + .01), pad = { l: 30, r: 8, t: 8, b: 18 }; const x = i => pad.l + (width - pad.l - pad.r) * i / 143; const y = v => pad.t + (height - pad.t - pad.b) * (1 - (v - min) / (max - min)); ctx.clearRect(0, 0, width, height); ctx.strokeStyle = '#e0e7e1'; ctx.fillStyle = '#87958e'; ctx.font = '9px DM Mono, monospace'; for (let i = 0; i < 3; i++) { const yy = pad.t + (height - pad.t - pad.b) * i / 2; ctx.beginPath(); ctx.moveTo(pad.l, yy); ctx.lineTo(width - pad.r, yy); ctx.stroke(); ctx.fillText(Number(max - (max - min) * i / 2).toFixed(2), 1, yy + 3); } const line = (values, color, dash) => { ctx.beginPath(); values.forEach((value, i) => i ? ctx.lineTo(x(i), y(value)) : ctx.moveTo(x(i), y(value))); ctx.strokeStyle = color; ctx.lineWidth = 1.8; ctx.setLineDash(dash); ctx.stroke(); ctx.setLineDash([]); }; line(price.baseline_yuan_kwh, '#317cb7', []); line(price.forecast_yuan_kwh, '#dc6d57', [5, 4]); line(price.actual_yuan_kwh, '#b72230', []); $('#q4PriceModel').textContent = price.model || 'ARX'; $('#q4PriceDate').textContent = state.date; }
function renderCompare() {
  const values = state.compareMode === 'cost' ? [{ id: 'Q2', name: 'Q2 · 计划成本', value: frozen.q2_plan_cost_yuan, display: frozen.q2_plan_cost_yuan ? `${fmt(frozen.q2_plan_cost_yuan / 1e6, 2)} M 元` : '—' }, { id: 'M3', name: 'Q3-M3 · 计划成本', value: frozen.m3_plan_cost_yuan, display: frozen.m3_plan_cost_yuan ? `${fmt(frozen.m3_plan_cost_yuan / 1e6, 2)} M 元` : '—' }, { id: 'Q4-2', name: 'Q4-2 · 计划成本', value: frozen.q4_2_plan_cost_yuan, display: frozen.q4_2_plan_cost_yuan ? `${fmt(frozen.q4_2_plan_cost_yuan / 1e6, 2)} M 元` : '—' }, { id: 'Q4-3', name: 'Q4-3 · 计划成本', value: frozen.q4_3_plan_cost_yuan, display: frozen.q4_3_plan_cost_yuan ? `${fmt(frozen.q4_3_plan_cost_yuan / 1e6, 2)} M 元` : '—' }] : [{ id: 'Q2', name: 'Q2 · 长周期', value: frozen.q2_emergency_kwh, display: `${fmt(frozen.q2_emergency_kwh, 0)} kWh` }, { id: 'M3', name: 'M3 · +18:00', value: frozen.m3_emergency_kwh, display: `${fmt(frozen.m3_emergency_kwh, 0)} kWh` }];
  const max = Math.max(...values.filter(item => item.value != null).map(item => item.value), 1); $('#compareList').innerHTML = values.map(item => `<div class="compare-row"><span class="compare-id">${item.id}</span><span class="compare-name">${item.name}</span><span class="compare-track"><i class="compare-fill" style="width:${item.value == null ? 0 : Math.max(2, item.value / max * 100)}%"></i></span><span class="compare-value">${item.display}</span></div>`).join('');
}
const _renderCompare = renderCompare; renderCompare = () => { _renderCompare(); const context = $('#q1ContextValue'); if (context) context.textContent = state.compareMode === 'cost' ? `${fmt(frozen.q1_cost_yuan || 0, 2)} 元/日` : '0 kWh/日'; };
function renderSoc() { const values = selectedStrategy()?.battery?.soc_kwh || [6000]; const max = state.data?.meta?.capacity_kwh || 12000; $('#socChart').innerHTML = values.map((value, index) => `<div class="soc-bar-col"><span class="soc-val">${fmt(value)}</span><i class="soc-bar-fill" style="height:${Math.max(4, value / max * 100)}%"></i><span class="soc-time">${index === 0 ? '0:00' : index === values.length - 1 ? '24:00' : `${index * 4}:00`}</span></div>`).join(''); }
function renderReplay(slot) {
  const day = dateData(); const actual = day?.actual; if (!actual) return;
  state.replaySlot = Math.max(0, Math.min(143, Number(slot))); const current = state.replaySlot; $('#replayTime').textContent = slotLabel(current); $('#authorityText').textContent = `当前为 ${slotLabel(current)}`;
  const net = actual.load_kw.map((value, index) => value - actual.pv_kw[index]); const forecast = day.causal?.center_net_kw || [];
  const max = Math.max(...net, ...forecast, 1); const points = values => values.map((value, index) => `${(index / 143) * 100},${100 - (Math.max(0, value) / max) * 82 - 8}`).join(' '); const past = net.slice(0, current + 1);
  const actualPoints = past.map((value, index) => `${(index / 143) * 100},${100 - (Math.max(0, value) / max) * 82 - 8}`).join(' '); const forecastPoints = points(forecast.length ? forecast : net);
  $('#replayPlot').innerHTML = `<svg class="replay-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="因果净负荷回放"><polyline class="replay-forecast-line" points="${forecastPoints}"/><polyline class="replay-actual-line" points="${actualPoints}"/><line class="replay-axis-line" x1="${(current / 143) * 100}" x2="${(current / 143) * 100}" y1="0" y2="100"/></svg><div class="replay-curtain" style="--left:${(current + 1) / 144 * 100}%"></div><div class="replay-legend"><span><i class="actual-key"></i>Actual（已发生）</span><span><i class="forecast-key"></i>Forecast（当前可用）</span></div>`;
  const futurePriceKnown = state.strategy === 'Q2' || state.strategy === 'Q3-M3'; const updateNodes = state.strategy === 'Q3-M3' ? [36,72,108] : state.strategy === 'Q4-3' ? [36,72,108] : []; const nextNode = updateNodes.find(node => node > current); const authority = futurePriceKnown ? '未来分时电价已知' : '未来动态实际电价未知，仅可用因果价格预测'; const contract = updateNodes.length ? (updateNodes.includes(current) ? `当前开放合同重评估（${slotLabel(current)}）` : `合同更新节点：${updateNodes.map(node => slotLabel(node)).join(' / ')}`) : '普通购电合同在日内固定'; $('#authorityList').innerHTML = `<div class="allowed">✓ <span>已发生负荷 / PV 与当前 SOC</span></div><div class="${futurePriceKnown ? 'allowed' : 'blocked'}">${futurePriceKnown ? '✓' : '×'} <span>${authority}</span></div><div class="allowed">✓ <span>最近一次已发布预测（${day.causal?.selected_predictor || '因果路径'}）</span></div><div class="${updateNodes.includes(current) ? 'allowed' : 'blocked'}">${updateNodes.includes(current) ? '✓' : '×'} <span>${contract}</span></div><div class="blocked">× <span>当前时刻后的真实负荷 / PV${futurePriceKnown ? '' : ' / 电价'}</span></div>`; $('#authorityNote').textContent = nextNode == null ? '本日没有新的合同窗口' : `下一权限节点 ${slotLabel(nextNode)}`;
}
function showQuestion(key) { state.question = key; $('#modelView').hidden = key === 'overview' || key === 'lab'; $('#labView').hidden = key !== 'lab'; $$('.question-view').forEach(view => view.hidden = true); const target = $(`#${key}View`); if (target) target.hidden = false; $('#viewName').textContent = ({ overview: '系统总览', q1: '确定性调度', q2: '风险感知 / 因果回放', q3: '多时刻更新 / 信息价值', q4: '因果电价', lab: '场景实验室' })[key] || '系统总览'; if (key === 'q2') renderReplay(state.replaySlot); if (key === 'q4') requestAnimationFrame(drawQ4Price); if (key !== 'overview') (key === 'lab' ? $('#labView') : $('#modelView')).scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function parseExpertText(text) { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length !== 145) throw new Error('Expert CSV 需要表头加 144 行数据'); const headers = lines[0].split(',').map(x => x.trim()); const required = ['time', 'load_kw', 'pv_kw', 'price_yuan_kwh']; const indexes = Object.fromEntries(required.map(key => [key, headers.indexOf(key)])); if (required.some(key => indexes[key] < 0)) throw new Error('必须包含 time, load_kw, pv_kw, price_yuan_kwh 列'); const out = Object.fromEntries(required.slice(1).map(key => [key, []])); lines.slice(1).forEach(line => { const cells = line.split(','); required.slice(1).forEach(key => { const value = Number(cells[indexes[key]]); if (!Number.isFinite(value) || value < 0) throw new Error(`${key} 存在非法值`); out[key].push(value); }); }); return out; }
async function requestJson(path, options = {}, timeoutMs = 120000) { setSolverStatus('waking', '正在唤醒优化求解器…'); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); let response = null; try { response = await fetch(`${API_BASE_URL}${path}`, { ...options, signal: controller.signal }); const body = await response.json().catch(() => ({})); if (!response.ok) { if (path === '/api/health') setSolverStatus('offline', '健康检查未通过'); else setSolverStatus('online', 'API 已连接 · 输入或模型请求需要修正'); throw new Error(body.detail || `API HTTP ${response.status}`); } setSolverStatus('online', 'Q1/Q2/Q3/Q4 online'); return body; } catch (error) { const message = error?.name === 'AbortError' ? '求解器响应超时，Render 可能仍在冷启动。' : (error?.message || '无法连接在线求解器'); if (!response) setSolverStatus('offline', message); else if (path === '/api/health') setSolverStatus('offline', message); throw new Error(message); } finally { clearTimeout(timer); } }
async function checkSolver() { try { await requestJson('/api/health', { method: 'GET' }, 30000); return true; } catch (_error) { return false; } }
async function postJson(path, payload) { return requestJson(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); }
async function postForm(path, form) { return requestJson(path, { method: 'POST', body: form }); }
async function postScenario(payload) { return postJson('/api/scenario/solve', payload); }
function drawScenarioChart(result) { const canvas = $('#scenarioChart'); if (!canvas) return; const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; const width = Math.max(300, rect.width), height = rect.height || 250; canvas.width = width * dpr; canvas.height = height * dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr, dpr); const series = [{ key: 'grid_kwh', color: '#317cb7', label: 'Grid' }, { key: 'charge_kwh', color: '#36d2b9', label: 'Charge' }, { key: 'discharge_kwh', color: '#dc6d57', label: 'Discharge' }, { key: 'spill_kwh', color: '#a8b4ae', label: 'Spill' }]; const max = Math.max(...series.flatMap(item => result[item.key] || []), 1); const pad = { l: 32, r: 12, t: 12, b: 25 }; const x = i => pad.l + (width - pad.l - pad.r) * i / 143; const y = value => pad.t + (height - pad.t - pad.b) * (1 - value / max); ctx.clearRect(0, 0, width, height); ctx.strokeStyle = '#dbe4dd'; ctx.fillStyle = '#82928a'; ctx.font = '9px DM Mono, monospace'; for (let i = 0; i < 3; i++) { const yy = pad.t + (height - pad.t - pad.b) * i / 2; ctx.beginPath(); ctx.moveTo(pad.l, yy); ctx.lineTo(width - pad.r, yy); ctx.stroke(); ctx.fillText(fmt(max * (1 - i / 2), 0), 2, yy + 3); } for (const item of series) { const values = result[item.key] || []; if (!values.length) continue; ctx.beginPath(); values.slice(0, 144).forEach((value, i) => i ? ctx.lineTo(x(i), y(value)) : ctx.moveTo(x(i), y(value))); ctx.strokeStyle = item.color; ctx.lineWidth = 1.8; ctx.stroke(); } const soc = result.soc_kwh || []; if (soc.length) { const socMax = 12000; ctx.beginPath(); soc.forEach((value, i) => i ? ctx.lineTo(x(Math.min(143, i)), pad.t + (height - pad.t - pad.b) * (1 - value / socMax)) : ctx.moveTo(x(0), pad.t + (height - pad.t - pad.b) * (1 - value / socMax))); ctx.strokeStyle = '#104680'; ctx.setLineDash([4, 4]); ctx.stroke(); ctx.setLineDash([]); } ctx.fillStyle = '#82928a'; ctx.fillText('00:00', pad.l, height - 6); ctx.fillText('12:00', width / 2 - 14, height - 6); ctx.fillText('24:00', width - 40, height - 6); }
function renderScenario(result) { const metrics = result.metrics || {}; const total = metrics.total_cost_yuan ?? (metrics.plan_cost_yuan || 0) + (metrics.emergency_cost_yuan || 0); $('#labResult').hidden = false; $('#labResult').innerHTML = `<div class="lab-result-head"><span class="card-kicker">SOLVER RESULT · ${result.source || result.mode}</span><span class="result-ok">NON-ANTICIPATIVE MODEL</span></div><div class="lab-result-grid"><div><span>总成本</span><b>${fmt(total, 2)} 元</b></div><div><span>普通购电</span><b>${fmt(metrics.grid_energy_kwh ?? metrics.grid_energy_kwh ?? 0)} kWh</b></div><div><span>充电 / 放电</span><b>${fmt(metrics.charge_energy_kwh || 0)} / ${fmt(metrics.discharge_energy_kwh || 0)} kWh</b></div><div><span>端点 SOC</span><b>${fmt(metrics.initial_soc_kwh ?? (result.soc_kwh || [0])[0])} → ${fmt(metrics.terminal_soc_kwh ?? (result.soc_kwh || [0]).at(-1))} kWh</b></div></div><div class="scenario-chart-wrap"><canvas id="scenarioChart" aria-label="144个十分钟求解结果"></canvas><div class="scenario-chart-note">Grid · Charge · Discharge · Spill · SOC虚线 · 144 × 10 min</div></div><p class="lab-note">${result.alpha_note || `预测器：${result.selected_predictor || '—'} · α = ${result.alpha ?? '—'} · 非预见性：${result.non_anticipative ? '是' : '—'}`}</p>`; drawScenarioChart(result); localStorage.setItem('gridscope_last_scenario', JSON.stringify({ at: new Date().toISOString(), metrics })); }
async function runQuick() { const button = $('#runQuick'); button.disabled = true; $('#labError').hidden = true; try { renderScenario(await postScenario({ mode: 'quick', base_date: $('#labBaseDate').value, load_multiplier: Number($('#loadMultiplier').value), pv_multiplier: Number($('#pvMultiplier').value), price_multiplier: Number($('#priceMultiplier').value), initial_soc_percent: Number($('#initialSoc').value) })); } catch (error) { showLabError(error); } finally { button.disabled = false; } }
async function runExpert() { const button = $('#runExpert'); button.disabled = true; $('#labError').hidden = true; try { const parsed = parseExpertText($('#expertCsv').value); renderScenario(await postScenario({ mode: 'expert', ...parsed, initial_soc_percent: Number($('#expertSoc').value) })); } catch (error) { showLabError(error); } finally { button.disabled = false; } }
async function runForecast() { const button = $('#runForecast'); button.disabled = true; $('#labError').hidden = true; try { let result; const common = { date: $('#forecastDate').value, initial_soc_percent: Number($('#forecastSoc').value), alpha: Number($('#forecastAlpha').value) }; if (state.forecastFile) { const form = new FormData(); form.append('file', state.forecastFile); Object.entries(common).forEach(([key, value]) => form.append(key, value)); result = await postForm('/api/forecast/solve-file', form); } else { result = await postJson('/api/forecast/solve', { ...common, history_days: Object.keys(state.data?.days || {}).length + 31 }); } renderScenario({ ...result, source: `Q2 ${result.date}` }); } catch (error) { showLabError(error); } finally { button.disabled = false; } }
function renderWhy(slot) { const actual = dateData()?.actual; const strategy = selectedStrategy(); if (!actual || !strategy) return; const block = Math.min(5, Math.floor(slot / 24)); const battery = strategy.battery; const startSoc = battery?.soc_kwh?.[block] ?? null; const canAdjust = (state.strategy === 'Q3-M3' || state.strategy === 'Q4-3') && [36, 72, 108].includes(slot); const plan = strategy.plan_kwh?.[slot]; const adjusted = strategy.adjusted_plan_kwh?.[slot]; const action = plan == null ? '结果中没有该时段计划' : plan > 0 ? '合同已覆盖当前净负荷，储能按约束优化' : '当前计划为 0，依赖光伏/储能与实时补缺'; $('#whyDrawer').innerHTML = `<b>${slotLabel(slot)} · ${state.strategy}</b><div class="why-grid"><span>负荷</span><b>${fmt(actual.load_kw[slot])} kW</b><span>PV</span><b>${fmt(actual.pv_kw[slot])} kW</b><span>价格</span><b>${Number(actual.price_yuan_kwh[slot]).toFixed(4)} 元/kWh</b><span>计划合同</span><b>${plan == null ? '—' : fmt(plan)} kWh</b><span>调整权限</span><b>${canAdjust ? '允许（节点窗口）' : '不可修改'}</b><span>4 h 电池块</span><b>${startSoc == null ? '—' : `SOC ${fmt(startSoc)} kWh`}</b></div><p>${action}${adjusted != null && plan != null && Math.abs(adjusted - plan) > 1e-6 ? `；调整后 ${fmt(adjusted)} kWh` : ''}。紧急购电在结果工作簿中以连续事件汇总。</p>`; }
const _renderReplay = renderReplay; renderReplay = slot => { _renderReplay(slot); renderWhy(Number(slot)); };
function layoutTwin() {
  const scene = $('.dt-scene'); const svg = $('.dt-lines'); const center = $('.dt-center'); if (!scene || !svg || !center) return;
  const svgRect = svg.getBoundingClientRect(); if (!svgRect.width || !svgRect.height) return; const scaleX = 1000 / svgRect.width; const scaleY = 190 / svgRect.height;
  const point = (selector, side) => { const element = $(selector); if (!element) return null; const rect = element.getBoundingClientRect(); const x = side === 'right' ? rect.right : side === 'left' ? rect.left : rect.left + rect.width / 2; const y = side === 'top' ? rect.top : side === 'bottom' ? rect.bottom : rect.top + rect.height / 2; return { x: (x - svgRect.left) * scaleX, y: (y - svgRect.top) * scaleY }; };
  const busLeft = point('.dt-center', 'left'), busRight = point('.dt-center', 'right'), busTop = point('.dt-center', 'top'), busBottom = point('.dt-center', 'bottom'); const grid = point('.dt-grid', 'right'), load = point('.dt-load', 'left'), pv = point('.dt-pv', 'bottom'), battery = point('.dt-battery', 'top');
  const set = (id, a, b) => { const path = $(`#${id}`); if (path && a && b) path.setAttribute('d', `M${a.x.toFixed(1)} ${a.y.toFixed(1)} L${b.x.toFixed(1)} ${b.y.toFixed(1)}`); }; set('flowGrid', grid, busLeft); set('flowLoad', busRight, load); set('flowPv', pv, busTop); set('flowBattery', busBottom, battery);
}
function wire() {
  $('#dateSelect').addEventListener('change', event => { state.date = event.target.value; $('#labBaseDate').value = state.date; renderDay(); if (state.question === 'q2') renderReplay(state.replaySlot); }); $('#strategySelect').addEventListener('change', event => { state.strategy = event.target.value; renderDay(); if (state.question === 'q2') renderReplay(state.replaySlot); }); $$('.legend-btn').forEach(button => button.addEventListener('click', () => { const key = button.dataset.series; state.activeSeries.has(key) ? state.activeSeries.delete(key) : state.activeSeries.add(key); button.classList.toggle('active'); drawProfile(); })); $('#compareSelect').addEventListener('change', event => { state.compareMode = event.target.value; renderCompare(); }); $$('.nav-item').forEach(button => button.addEventListener('click', () => { $$('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); showQuestion(button.dataset.question); })); $('#replayRange').max = 143; $('#replayRange').addEventListener('input', event => renderReplay(event.target.value)); $('#playReplay').addEventListener('click', () => { const button = $('#playReplay'); if (state.replayTimer) { clearInterval(state.replayTimer); state.replayTimer = null; button.textContent = '▶ 播放'; return; } button.textContent = 'Ⅱ 暂停'; state.replayTimer = setInterval(() => { const next = (state.replaySlot + 1) % 144; $('#replayRange').value = next; renderReplay(next); }, 380); }); $('#whyAction').addEventListener('click', () => { const drawer = $('#whyDrawer'); drawer.hidden = !drawer.hidden; if (!drawer.hidden) renderWhy(state.replaySlot); }); $('#specBtn').addEventListener('click', () => { $('#specDrawer').hidden = false; $('#specDrawer').scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }); $('#closeSpec').addEventListener('click', () => { $('#specDrawer').hidden = true; }); $('#runQuick').addEventListener('click', runQuick); $('#runExpert').addEventListener('click', runExpert); $('#runForecast').addEventListener('click', runForecast); $$('.lab-mode-btn').forEach(button => button.addEventListener('click', () => { $$('.lab-mode-btn').forEach(item => item.classList.remove('active')); button.classList.add('active'); $$('.lab-form').forEach(form => form.hidden = true); $(`#${button.dataset.labMode}Form`).hidden = false; }));
  $('#expertFile').addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; const form = new FormData(); form.append('file', file); form.append('initial_soc_percent', $('#expertSoc').value); $('#labError').hidden = true; try { renderScenario(await postForm('/api/scenario/solve-file', form)); } catch (error) { showLabError(error); } });
  $('#forecastFile').addEventListener('change', event => { state.forecastFile = event.target.files[0] || null; });
  $('#solverRetry').addEventListener('click', async () => { $('#solverRetry').hidden = true; setSolverStatus('waking', '正在唤醒优化求解器…'); await checkSolver(); });
  $('#userMenuToggle').addEventListener('click', event => { event.stopPropagation(); const menu = $('#userMenu'); menu.hidden = !menu.hidden; $('#userMenuToggle').setAttribute('aria-expanded', String(!menu.hidden)); if (!menu.hidden) menu.querySelector('button').focus(); }); document.addEventListener('click', event => { if (!$('#userMenu').contains(event.target) && !$('#userMenuToggle').contains(event.target)) { $('#userMenu').hidden = true; $('#userMenuToggle').setAttribute('aria-expanded', 'false'); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { $('#userMenu').hidden = true; $('#userMenuToggle').setAttribute('aria-expanded', 'false'); } }); $('#sourceMenu').addEventListener('click', () => { $('#userMenu').hidden = true; $('#specBtn').click(); }); $('#densityMenu').addEventListener('click', () => { document.body.classList.toggle('compact-mode'); $('#userMenu').hidden = true; }); $('#exportMenu').addEventListener('click', () => { const payload = { schema: state.data?.schema_version, date: state.date, strategy: state.strategy, snapshot: state.data?.frozen_metrics }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `gridscope-${state.date}.json`; link.click(); URL.revokeObjectURL(link.href); $('#userMenu').hidden = true; }); window.addEventListener('resize', () => { drawProfile(); layoutTwin(); }); $('#refreshBtn').addEventListener('click', () => { renderDay(); layoutTwin(); const button = $('#refreshBtn'); button.textContent = '✓'; setTimeout(() => { button.textContent = '↻'; }, 700); });
}
document.addEventListener('DOMContentLoaded', async () => { wire(); const twin = $('.dt-scene'); if (twin && 'ResizeObserver' in window) { new ResizeObserver(() => requestAnimationFrame(layoutTwin)).observe(twin); } requestAnimationFrame(layoutTwin); if (document.fonts?.ready) document.fonts.ready.then(() => requestAnimationFrame(layoutTwin)); try { await loadSnapshot(); } catch (error) { $('#snapshotStatus').textContent = `SNAPSHOT ERROR · ${error.message}`; $('#snapshotStatus').classList.add('error-status'); } checkSolver(); });
